default:
  tags:
    - devsecops-instance

stages:
  - build
  - convert

build_report:
  stage: build
  image: python:3.10-slim
  before_script:
    - pip install requests
  script:
    - python build_report.py
  artifacts:
    paths:
      - report.html
      - vul.json

pdf_conversion:
  stage: convert
  image: alpine
  before_script:
    - apk add --no-cache chromium --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/main
  script:
    - DIR=$(pwd)
    - chromium --headless --disable-gpu --no-sandbox --print-to-pdf file://$DIR/report.html
  artifacts:
    paths:
      - output.pdf